# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: 基本ユーザ管理API


parameters:
  uid:
    name: uid
    in: path
    description: メッセージID
    type: string
    required: true
  mailtoken:
    name: X-MAILTOKEN
    in: header
    description: メールトークン
    type: string
    required: true

# Describe your paths here
paths:
  /message:
    get:
      description: メッセージを検索します。
      parameters:
        -
          name: conj
          in: query
          description: 検索条件
          type: string
          required: true
      responses:
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              message:
                $ref: '#/definitions/Message'
    post:
      description: メッセージを投稿します。
      parameters:
        -
          name: message
          in: query
          description: メッセージボディ
          type: string
          required: true
      responses:
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              message:
                $ref: '#/definitions/Message'
  # This is a path endpoint. Change it.
  /message/{uid}:
    get:
      description: メッセージを取得します。
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              message:
                $ref: '#/definitions/Message'
    put:
      description: メッセージを更新します。
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              message:
                $ref: '#/definitions/Message'
    delete:
      description: メッセージを削除します。
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        200:
          description: Successful response
          schema:
            title: Result
            type: object
            properties:
              message:
                $ref: '#/definitions/Message'
definitions:
  Message:
    type: object
    properties:
      from:
        type: string
      to:
        type: string
      body:
        type: string